# Generated by Django 5.1.7 on 2025-03-27 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('question', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='help_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_questions', to='pets.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Help',
        ),
    ]
