# Generated by Django 5.1.7 on 2025-03-09 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
